default: &default
  adapter: mysql2
  database: espnsports_rails
  username: ysportsrdsebs
  password: testing122
  host: aa16q025m64czad.ccnau5d9vc6f.us-west-2.rds.amazonaws.com
  port: 3306
  reconnect: true

development:
  <<: *default
test:
  <<: *default
production:
  <<: *default
